/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.sql.*;
import java.util.ArrayList;
import backend.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author G512
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    
    ArrayList<Kategori> arrKategori = new ArrayList<>();
    boolean st_edit;
    String sql, namabarang;
    int idbarang, idkategori, harga, stok;
    
    public Barang() {
        initComponents();
        
        idbarang = 0;
        st_edit = false;
        showData(null);
        tanggal();
        loadKategori();
    }
    
    private void clear(){
        jTextField_nama.setText( null );
        jTextField_harga.setText( null );
        jTextField_stok.setText( null );
    }
    
    public void tanggal(){
        Date now = new Date();  
        jDateChooser1.setDate(now);
    }
    
    private void showData( String cari ){
        if ( cari == null ){
            sql = "SELECT "
                    + "idbarang AS ID, "
                    + "namabarang AS NAMA, "
                    + "harga AS HARGA, "
                    + "stok AS STOK, "
                    + "tanggal AS DATE, "
                    + "namakategori AS KATEGORI "
                    + "FROM view_kategoribarang ";
        }else{
            sql = "SELECT "
                    + "idbarang AS ID, "
                    + "namabarang AS NAMA, "
                    + "harga AS HARGA, "
                    + "stok AS STOK, "
                    + "tanggal AS DATE,"
                    + "namakategori AS KATEGORI "
                    + "FROM view_kategoribarang "
                    + "WHERE namabarang LIKE '%"+ cari +"%' ";
        }
        
        try {
            //MENAMPILKAN DATA PADA TABEL
            ResultSet rs = koneksi.Database.read(sql);
            jTable_barang.setModel( DbUtils.resultSetToTableModel(rs));
            koneksi.Database.closeDB();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog( null, e);
        }
    }
    
    private void loadKategori(){
        jComboBox_kategori.removeAllItems();
        try {
            ResultSet rs = koneksi.Database.read( "SELECT idkategori, namakategori FROM kategori " );
            
            while( rs.next() ){
                arrKategori.add( new Kategori( Integer.parseInt ( rs.getString("idkategori") ),rs.getString("namakategori")));
            }
            
            //MENGAMBIL DATA DARI CLASS KATEGORI UNTUK DITAMPILKAN DI COMBOBOX
            for( int i = 0; i < arrKategori.size(); i++ ){
                jComboBox_kategori.addItem( arrKategori.get( i ).getNamaKategori());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_kategori = new javax.swing.JComboBox<>();
        jTextField_nama = new javax.swing.JTextField();
        jTextField_harga = new javax.swing.JTextField();
        jTextField_stok = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_search = new javax.swing.JButton();
        jTextField_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_barang = new javax.swing.JTable();
        jButton_delete = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jComboBox_kategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_kategoriActionPerformed(evt);
            }
        });

        jTextField_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_stok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stokActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setText("DATA BARANG ERAMART");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NAMA BARANG");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("KATEGORI BARANG");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("HARGA BARANG");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("TANGGAL MASUK");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("STOK BARANG");

        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_add.setText("ADD");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_clear.setText("REFRESH");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_search.setText("SEARCH");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });

        jTable_barang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_barang);

        jButton_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_back.setText("BACK");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_search)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_search)
                    .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_back)
                    .addComponent(jButton_clear))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDateChooser1.setEnabled(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stokActionPerformed

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed

    private void jTable_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_barangMouseClicked
        // TODO add your handling code here:
        
        st_edit = true;
        int baris = jTable_barang.getSelectedRow();
        
        idbarang = Integer.parseInt(jTable_barang.getModel().getValueAt(baris, 0).toString() );
        
        //ambil data berdasarkan id
        sql = "SELECT * FROM barang WHERE idbarang = "+idbarang;
        
        try {
            ResultSet rs = koneksi.Database.read(sql);
            
            while( rs.next() ){
                jTextField_nama.setText( rs.getString("namabarang"));
                jTextField_harga.setText( rs.getString("harga"));
                jTextField_stok.setText(rs.getString("stok"));
                
                String tanggal = jTable_barang.getValueAt(baris,4).toString();
                Date convert = null;
                try{
                    convert = new SimpleDateFormat("yyyy-MM-dd").parse(tanggal);   
                }catch(Exception e){
                    System.out.println(e);
                }
                jDateChooser1.setDate(convert);
                
                idkategori = rs.getInt("idkategori");
                
                for( int i = 0; i < arrKategori.size(); i++)
                    if ( idkategori == arrKategori.get(i).getIdKategori() )
                        jComboBox_kategori.setSelectedIndex(i);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null, ex.toString() );
        }
    }//GEN-LAST:event_jTable_barangMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal2 = date.format(jDateChooser1.getDate());
        
        if ( st_edit == false ){ //simpan
            sql = "INSERT INTO barang( idkategori, namabarang, harga, stok, tanggal) "
                    + "VALUES( "+ idkategori +", "
                    + "'"+ jTextField_nama.getText().trim()  +"', "
                    + "'"+ jTextField_harga.getText().trim() +"', "
                    + "'"+ jTextField_stok.getText().trim()  +"', "
                    + "'"+ tanggal2 +"' )";
        }else{ //update / perbarui
            sql = "UPDATE barang SET idkategori = "+ idkategori +", "
                    + "namabarang = '"+ jTextField_nama.getText().trim() +"', "
                    + "harga = '"+ jTextField_harga.getText().trim() +"', "
                    + "stok = '"+ jTextField_stok.getText().trim() +"', "
                    + "tanggal = '"+ tanggal2 +"' "
                    + "WHERE idbarang = "+ idbarang;
        }
        boolean berhasil = false;
        
        try {
            berhasil = koneksi.Database.exec(sql);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null, ex );
        }
        
        if ( berhasil ){
            clear();
            showData( null );
            st_edit = false;
            idbarang = 0;
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Eksekusi Data");
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // TODO add your handling code here:
        showData( jTextField_search.getText().trim());
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jComboBox_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_kategoriActionPerformed
        // TODO add your handling code here:
        
        int idx = jComboBox_kategori.getSelectedIndex();
        
        if ( arrKategori.size() > 0 ){
            idkategori = arrKategori.get(idx).getIdKategori();
        }
    }//GEN-LAST:event_jComboBox_kategoriActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        
        int respon = JOptionPane.showConfirmDialog(null, 
                "Hapus " + jTextField_nama.getText().trim() + " ?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        
        if ( respon == JOptionPane.YES_OPTION ){ //hapus
            sql = "DELETE FROM barang WHERE idbarang = "+ idbarang;
            
            boolean berhasil = false;
            try {
                berhasil = koneksi.Database.exec(sql);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog( null, ex );
            }
            
            if ( berhasil ){
                clear();
                showData( null );
                st_edit = false;
                idbarang = 0;
            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Dihapus");
            }
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        clear();
        showData(null);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_search;
    private javax.swing.JComboBox<String> jComboBox_kategori;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_barang;
    private javax.swing.JTextField jTextField_harga;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_search;
    private javax.swing.JTextField jTextField_stok;
    // End of variables declaration//GEN-END:variables
}
